"""Sprint 0 : tables entreprise, client, fournisseur

Revision ID: 1e63afce3438
Revises: 
Create Date: 2026-04-23 13:51:50.181614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e63afce3438'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('adresse_fact', sa.String(length=255), nullable=True),
    sa.Column('cp_fact', sa.String(length=10), nullable=True),
    sa.Column('ville_fact', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=30), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entreprise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('tel', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pct_fg', sa.Float(), nullable=True),
    sa.Column('pct_marge_defaut', sa.Float(), nullable=True),
    sa.Column('heures_prod_presse_mois', sa.Integer(), nullable=True),
    sa.Column('heures_prod_finition_mois', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fournisseur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=30), nullable=True),
    sa.Column('conditions_paiement', sa.String(length=100), nullable=True),
    sa.Column('delai_livraison_j', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fournisseur')
    op.drop_table('entreprise')
    op.drop_table('client')
    # ### end Alembic commands ###
