"""Sprint 3 cost engine reference tables

Revision ID: 716126871532
Revises: 882ea105e9ef
Create Date: 2026-04-28 09:14:55.696547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716126871532'
down_revision: Union[str, Sequence[str], None] = '882ea105e9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_machine_mensuelle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('heures_disponibles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cout_horaire_calcule', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('annee >= 2024', name='ck_charge_machine_annee'),
    sa.CheckConstraint('mois BETWEEN 1 AND 12', name='ck_charge_machine_mois'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mois', 'annee', name='uq_charge_machine_mois_annee')
    )
    op.create_table('correspondance_laize_metrage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('laize_cm', sa.Integer(), nullable=False),
    sa.Column('metrage_metres', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laize_cm')
    )
    op.create_table('tarif_encre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_encre', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('prix_kg_defaut', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prix_kg_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prix_kg_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ratio_g_m2_couleur', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_encre')
    )
    op.create_table('tarif_poste',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cle', sa.String(length=50), nullable=False),
    sa.Column('poste_numero', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('valeur_defaut', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valeur_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valeur_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unite', sa.String(length=30), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('poste_numero BETWEEN 1 AND 7', name='ck_tarif_poste_poste_numero'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle')
    )
    op.create_table('temps_operation_standard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle_operation', sa.String(length=150), nullable=False),
    sa.Column('minutes_standard', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle_operation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temps_operation_standard')
    op.drop_table('tarif_poste')
    op.drop_table('tarif_encre')
    op.drop_table('correspondance_laize_metrage')
    op.drop_table('charge_machine_mensuelle')
    # ### end Alembic commands ###
