"""Sprint 3 prep : calc params on machine + entreprise

Revision ID: 882ea105e9ef
Revises: e2f856763fca
Create Date: 2026-04-27 15:55:26.659108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882ea105e9ef'
down_revision: Union[str, Sequence[str], None] = 'e2f856763fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('taux_chutes_defaut', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('entreprise', sa.Column('ratio_encre_m2_couleur', sa.Numeric(precision=8, scale=6), nullable=True))
    op.add_column('entreprise', sa.Column('heures_productives_mensuelles', sa.Integer(), nullable=True))
    op.add_column('machine', sa.Column('vitesse_moyenne_m_h', sa.Integer(), nullable=True))
    op.add_column('machine', sa.Column('duree_calage_h', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'duree_calage_h')
    op.drop_column('machine', 'vitesse_moyenne_m_h')
    op.drop_column('entreprise', 'heures_productives_mensuelles')
    op.drop_column('entreprise', 'ratio_encre_m2_couleur')
    op.drop_column('entreprise', 'taux_chutes_defaut')
    # ### end Alembic commands ###
