"""Sprint 5 outil_decoupe table

Revision ID: addf7c687f84
Revises: 1a9cebb269d1
Create Date: 2026-04-28 14:44:23.506168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addf7c687f84'
down_revision: Union[str, Sequence[str], None] = '1a9cebb269d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outil_decoupe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('format_l_mm', sa.Integer(), nullable=False),
    sa.Column('format_h_mm', sa.Integer(), nullable=False),
    sa.Column('nb_poses_l', sa.Integer(), nullable=False),
    sa.Column('nb_poses_h', sa.Integer(), nullable=False),
    sa.Column('forme_speciale', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outil_decoupe')
    # ### end Alembic commands ###
