"""Sprint 4 add devis table

Revision ID: b89d835f3823
Revises: d72e394d8c52
Create Date: 2026-04-29 16:04:52.694051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89d835f3823'
down_revision: Union[str, Sequence[str], None] = 'd72e394d8c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_modification', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'valide', name='devis_statut_enum'), server_default='brouillon', nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('payload_input', sa.JSON(), nullable=False),
    sa.Column('payload_output', sa.JSON(), nullable=False),
    sa.Column('mode_calcul', sa.String(length=10), nullable=False),
    sa.Column('cylindre_choisi_z', sa.Integer(), nullable=True),
    sa.Column('cylindre_choisi_nb_etiq', sa.Integer(), nullable=True),
    sa.Column('ht_total_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('format_h_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('format_l_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_client_id'), 'devis', ['client_id'], unique=False)
    op.create_index('ix_devis_date_creation_desc', 'devis', ['date_creation'], unique=False)
    op.create_index(op.f('ix_devis_numero'), 'devis', ['numero'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_devis_numero'), table_name='devis')
    op.drop_index('ix_devis_date_creation_desc', table_name='devis')
    op.drop_index(op.f('ix_devis_client_id'), table_name='devis')
    op.drop_table('devis')
    # Drop explicite du type enum Postgres (no-op SQLite, cleanup propre Postgres).
    sa.Enum(name='devis_statut_enum').drop(op.get_bind(), checkfirst=True)
