"""Sprint 2 : tables machine operation_finition partenaire_st charge_mensuelle complexe catalogue

Revision ID: e2f856763fca
Revises: 1e63afce3438
Create Date: 2026-04-27 11:25:02.426790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f856763fca'
down_revision: Union[str, Sequence[str], None] = '1e63afce3438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_mensuelle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('categorie', sa.String(length=30), nullable=False),
    sa.Column('montant_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('largeur_max_mm', sa.Integer(), nullable=True),
    sa.Column('vitesse_max_m_min', sa.Integer(), nullable=True),
    sa.Column('nb_couleurs', sa.Integer(), nullable=True),
    sa.Column('cout_horaire_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('operation_finition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('unite_facturation', sa.String(length=20), nullable=False),
    sa.Column('cout_unitaire_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('temps_minutes_unite', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('partenaire_st',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raison_sociale', sa.String(length=150), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('contact_nom', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_tel', sa.String(length=30), nullable=True),
    sa.Column('prestation_type', sa.String(length=20), nullable=True),
    sa.Column('delai_jours_moyen', sa.Integer(), nullable=True),
    sa.Column('qualite_score', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raison_sociale')
    )
    op.create_table('catalogue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_produit', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('matiere', sa.String(length=100), nullable=True),
    sa.Column('format_mm', sa.String(length=50), nullable=True),
    sa.Column('nb_couleurs', sa.Integer(), nullable=True),
    sa.Column('prix_unitaire_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('frequence_estimee', sa.String(length=20), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_produit', 'client_id', name='uq_catalogue_code_client')
    )
    op.create_table('complexe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('famille', sa.String(length=50), nullable=False),
    sa.Column('face_matiere', sa.String(length=150), nullable=True),
    sa.Column('grammage_g_m2', sa.Integer(), nullable=True),
    sa.Column('adhesif_type', sa.String(length=50), nullable=True),
    sa.Column('prix_m2_eur', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseur.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complexe')
    op.drop_table('catalogue')
    op.drop_table('partenaire_st')
    op.drop_table('operation_finition')
    op.drop_table('machine')
    op.drop_table('charge_mensuelle')
    # ### end Alembic commands ###
